// Generated by CoffeeScript 1.7.1
(function() {
  var Email, auth_template, email, _;

  Email = require('email').Email;

  _ = require('underscore');

  auth_template = '<p><h1>Welcome: <%=to %></h1></p>' +
		'<p>To complete your registration please click on the activation link below ' +
		'or copy and paste it in your browser\'s address bar:' +
			'<a href="<%=url %>"><%=url %></a>' +
		'</p>';

	var forgot_tpl = '<p><h3>Forgot password!</h3><p><a href="<%=url %>">Reset password</a></p></p>';

  email = {
    successfuly_auth: function(from, to, url) {
      var auth_msg;
      auth_msg = new Email({
        from: from,
        to: to,
        subject: 'Noamay.com authentication',
        bodyType: 'html',
        body: _.template(auth_template, {
          to: to,
          url: url
        })
      });
      return auth_msg.send(function(err) {
        return console.log('Send email error:', err);
      });
    },
		forgot: function(from,to,url,cb){
			console.log("forgot password");
			forgotemail = new Email({
				from: from,
				to: to,
				subject: 'Noamay.com forgot password',
				bodyType: 'html',
				body: _.template(forgot_tpl, {
					url: url
				})
			});
			forgotemail.send(function(err){
				if(!err){
					cb();
				}else{
					cb(err);
				}
			});
			cb();
			return;
		}
  };

  module.exports = email;

}).call(this);

//# sourceMappingURL=email.map
