// Generated by CoffeeScript 1.7.1
(function() {
  var config, crypto;

  crypto = require('crypto');

  config = {
    secret: crypto.randomBytes(128).toString("base64"),
    alers: {},
    notify: {},
    host: '192.163.201.155:8082',
		workspace:'dev',
		c9path : '/home/naomay/cloud9/server.js'
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=global.map
